### ISSUE TITLE
Can not Sign in via GitHub 

### ISSUE THREAD

**Issue by thanidacwn** [MemoMood/MemoMood#53]
DoesNotExist at /accounts/github/login/

<img width="1440" alt="Screen Shot 2565-11-23 at 09 53 35" src="https://user-images.githubusercontent.com/92778351/203461017-a357cc34-2cca-4338-949c-76a193cb3e6a.png">

**Comment by panitnt** [comment]
Thanks for let me know but now, we remove these features. Sorry about that🙏🏻
