### ISSUE TITLE
Can access views of created mood even though im logged out

### ISSUE THREAD

**Issue by Hamiz5401** [MemoMood/MemoMood#56]
I can access any mood even though I'm logged out.
![image](https://user-images.githubusercontent.com/92782075/203466733-4cb2641d-71df-4f74-9048-acb306d0240c.png)
![image](https://user-images.githubusercontent.com/92782075/203466761-bbd00632-8000-42aa-8026-8aaa0d5d9e20.png)

**Comment by panitnt** [comment]
We already fix that user need to login. Thanks.
