### ISSUE TITLE
Can access other user mood

### ISSUE THREAD

**Issue by Hamiz5401** [MemoMood/MemoMood#57]
Can see other user mood pages.
![image](https://user-images.githubusercontent.com/92782075/203467142-05577be0-13cf-4ac2-b9ea-30476d8341ac.png)
![image](https://user-images.githubusercontent.com/92782075/203467189-02c372ae-4e46-4b8d-8552-6a8bfebfafbc.png)

**Comment by panitnt** [comment]
<img width="1328" alt="Screenshot 2565-11-23 at 11 16 09 AM" src="https://user-images.githubusercontent.com/92779345/203468344-7122dd97-5f0a-4e25-bf20-fbdca54ebe24.png">

Issus is fixed. You may try it again, please. Thank you for pointing this out
