### ISSUE TITLE
In view page. If I have no friends in activity it still show with message.

### ISSUE THREAD

**Issue by MarojT** [MemoMood/MemoMood#62]
![image](https://user-images.githubusercontent.com/59698469/203469618-47ff712b-ea28-47ca-9372-28735bc56609.png)

**Comment by panitnt** [comment]
Now, we already fix. This is example. Thanks.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/92779345/203571907-ff082706-f045-4574-91bd-1c34d46284a7.png">
