### ISSUE TITLE
Plain Sign In Page

### ISSUE THREAD

**Issue by Unikorn996** [MemoMood/MemoMood#63]
[<img width="1440" alt="Screenshot 2565-11-23 at 11 35 13" src="https://user-images.githubusercontent.com/88017778/203470281-70e6696c-1239-4d29-a6f9-b88cb55c6475.png">
](url)
Why the Login page both Google and GIthub look so plain?

**Comment by panitnt** [comment]
Now, we fixed
* Change new style in login page (ea34bbd93fdca880e36fbeb00f9f9d90e17af0f6)
* Change direct to google, skip third party page (b5c57ad9f28e4b7b6b6cb0dd6aa97154eb09b095)
* Change sign up page styles (c1b3ed535f861dda2b1a0e3039b268a09ff68370)
* Change logout page design (1b70834363fef2e9461ae94b524473d4b1c3ecac)

But all of this still waiting for deploy again.
Thanks.
