### ISSUE TITLE
When submit signup its show server error (500)

### ISSUE THREAD

**Issue by koonwill** [MemoMood/MemoMood#69]
![image](https://user-images.githubusercontent.com/93331101/203486263-666a0408-6e72-485e-88a9-9dc53e3c7161.png)

**Comment by koonwill** [comment]
I'm trying to signup by insert email username and password then its show this page after I submit.

**Comment by natekrth** [comment]
Fixed. We have problem with email input field when user sign up a new account
We close the issue for now feel free to open issue any time. Thank you for pointed out this issue. @koonwill
