### ISSUE TITLE
Apperance bug? : When I'm select the favorite mood to add, it doesn't show up that which mood I've selected.

### ISSUE THREAD

**Issue by oMojiko** [MemoMood/MemoMood#71]
![image](https://user-images.githubusercontent.com/91252217/203494148-47d43053-4030-4e9c-aa33-7fd1a23c6cb7.png)

**Comment by panitnt** [comment]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/92779345/203573178-0134c0d7-d0b3-4a76-9aa9-a5b8c8b74eb3.png">
Now, our styles can use in our web. You can also look again. Thanks
