### ISSUE TITLE
Can choose future date in archive.

### ISSUE THREAD

**Issue by Siripa-Maneein** [MemoMood/MemoMood#77]
<img width="293" alt="Screen Shot 2565-11-27 at 11 27 32" src="https://user-images.githubusercontent.com/92819559/204119236-77773b4f-a9e4-471d-9b19-f7b5c69721f6.png">

**Comment by panitnt** [comment]
Thanks. We already fixed in commit https://github.com/MemoMood/MemoMood/commit/dca08b9ada693d3ed0675de826bf68e839220157. Now, it is in progress to deploy.
