### ISSUE TITLE
Server 500 when input number in the box (Choose a week) in daily mood page.

### ISSUE THREAD

**Issue by Siripa-Maneein** [MemoMood/MemoMood#78]
<img width="491" alt="Screen Shot 2565-11-27 at 11 37 07" src="https://user-images.githubusercontent.com/92819559/204119439-5f88e8a5-0029-449b-b334-b44f90e63ee3.png">
<img width="1189" alt="Screen Shot 2565-11-27 at 11 34 30" src="https://user-images.githubusercontent.com/92819559/204119444-21f52681-9748-4947-b05d-6f2f5e827b7e.png">

**Comment by panitnt** [comment]
We already fix this issue (commit a6ad4741f54ecf592fca9d15d8b2faf2c4955940). And it is in progress in deploy this again. Thanks.
