### ISSUE TITLE
Server Error when enter place and friend as the same name 

### ISSUE THREAD

**Issue by khemissara** [MemoMood/MemoMood#79]
<img width="1440" alt="Screenshot 2565-11-27 at 12 36 04" src="https://user-images.githubusercontent.com/92781160/204120928-d8fb8fbc-1f6a-457e-ac21-14da82d701cf.png">

**Comment by panitnt** [comment]
Now, we already fixed them in 5612326bff890fde3eba2b948494d0a31aca18f6. But still waiting for deploy again. Thanks.
